In [2]:
import numpy as np

#create numpy array from list
sample_list = [1,2,3]
list_array = np.array(sample_list)
print(list_array)

#create numpy array from tuple
tup = (3,4,5)
my_tup_array = np.array(tup)
print(my_tup_array)

[1 2 3]
[3 4 5]


In [3]:
#Multiply two numpy arrays using loops
def multiply_loops(A, B):
    c=np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for k in range(B.shape[1]):
            c[i,k] = 0
            for j in range(B.shape[0]):
                n = A[i,j] * B[j,k]
                c[i,k] += n
    return c

In [4]:
#Multiply two numpy arrays using NumPy's vector multiplication
def multiply_vector(A, B):
     return A @ B

In [5]:
X = np.random.random((100, 100))
Y = np.random.random((100, 100))

%timeit multiply_loops(X, Y)
%timeit multiply_vector(X, Y)
%timeit np.dot(X,Y)

548 ms ± 8.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
27.7 µs ± 2.95 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
33.7 µs ± 4.97 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
#Create NumPy array with all zeros
tup_dim = (3, 4)
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
print(my_zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
#Create NumPy array with all ones
tup_dim = (3, 4)
my_ones_array = np.ones(tup_dim, dtype=np.int16)
print(my_ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [8]:
#Create NumPy array with specific value
tup_dim = (3, 4)
my_seven_array = np.full(tup_dim, 7, dtype=np.int16)
print(my_seven_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [9]:
#Create NumPy Identity matrix or array
my_identity_array = np.identity(4, dtype=np.float64)
print(my_identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
#Create NumPy matrix or array with random values
my_rand_array = np.random.rand(3,4)
print(my_rand_array)

[[0.40695034 0.533477   0.34465376 0.16172356]
 [0.76125966 0.12039704 0.25777012 0.37013137]
 [0.2534888  0.18048348 0.04031344 0.94996529]]


In [11]:
#Create NumPy array with uninitialized values
tup_dim = (3, 4)
my_uninitialized_array = np.empty(tup_dim)
print(my_uninitialized_array)

[[0.40695034 0.533477   0.34465376 0.16172356]
 [0.76125966 0.12039704 0.25777012 0.37013137]
 [0.2534888  0.18048348 0.04031344 0.94996529]]


In [12]:
#Create NumPy array with range of values - 
#start value(10), end value(30), gap value(5)
my_range_array = np.arange(10,30, 5)
print(my_range_array)

[10 15 20 25]


In [13]:
#Create NumPy array with equally spaced range of values - 
#start value(0), end value(5/3), total no. of values(6)
my_spaced_array = np.linspace(0,5/3, 6)
print(my_spaced_array)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [14]:
my_array = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])
print(my_array.ndim)
print(my_array.shape)
print(my_array.size)
print(my_array.dtype)
print(my_array.itemsize)

2
(3, 4)
12
int64
8


In [15]:
#Load txt file using loadtxt()

import os
import pandas as pd

# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'

# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))

# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]

# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

FILE = 'housing_short.csv'
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()
print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [16]:
#Load txt file using genfromtxt()

import os
import numpy as np

# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'

# reading the large housing.csv file using pandas
FILE = os.path.join(HOUSING_PATH, "housing.csv")

def load_housing_dataset(file = FILE ):
    return np.genfromtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)

result_arr = load_housing_dataset()
print(result_arr.size)
print(result_arr)

20640
[(-122.23, 37.88, 41.,  880.,  129.,  322.,  126., 8.3252, 452600., b'NEAR BAY')
 (-122.22, 37.86, 21., 7099., 1106., 2401., 1138., 8.3014, 358500., b'NEAR BAY')
 (-122.24, 37.85, 52., 1467.,  190.,  496.,  177., 7.2574, 352100., b'NEAR BAY')
 ...
 (-121.22, 39.43, 17., 2254.,  485., 1007.,  433., 1.7   ,  92300., b'INLAND')
 (-121.32, 39.43, 18., 1860.,  409.,  741.,  349., 1.8672,  84700., b'INLAND')
 (-121.24, 39.37, 16., 2785.,  616., 1387.,  530., 2.3886,  89400., b'INLAND')]


In [17]:
#Resize NumPy array - can create array of larger size than original

my_arr = np.array([[1,2,3,4],[5,6,7,8]])
my_arr.resize((3,4))
print(my_arr)

[[1 2 3 4]
 [5 6 7 8]
 [0 0 0 0]]


In [11]:
#Reshape NumPy array - same no. of elements as the original array

my_first_arr = np.array([1,2,3,4,5,6,7,8])
my_new_arr = my_first_arr.reshape((2,4))
print(my_new_arr)
print(my_first_arr)

#Reshaping when desired number of rows is unknown
my_second_arr = np.arange(9)
my_updated_arr = my_second_arr.reshape(-1,3)
print(my_updated_arr)
print(my_second_arr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [37]:
#Reversing NumPy array
my_orig_arr = np.array((1, 15, 3, 9, 26, 7, 89, 12))
my_rev_arr = my_orig_arr[::-1]
print(my_rev_arr)

[12 89  7 26  9  3 15  1]


In [38]:
#Replacing selected items in NumPy array
my_orig_arr2 = np.array((2, 9, 17, 13, 1, 4, 20, 57))
my_orig_arr2[2:5] = -6
print(my_orig_arr2)

[ 2  9 -6 -6 -6  4 20 57]


In [39]:
#Extracting slice of NumPy array
apple = np.array((1, 8, 23, 3, 18, 91, 7, 15))
apple_slice = apple[1 : 4]
print(apple_slice)
print(apple)

apple_slice[1] = 99999
print(apple_slice)
print(apple)

apple_slice_new = apple[2 : 5].copy()
apple_slice_new[1] = 222222
print(apple_slice_new)
print(apple)

[ 8 23  3]
[ 1  8 23  3 18 91  7 15]
[    8 99999     3]
[    1     8 99999     3    18    91     7    15]
[ 99999 222222     18]
[    1     8 99999     3    18    91     7    15]


In [2]:
from sklearn.datasets import load_sample_image 
import numpy as np

china = load_sample_image("china.jpg")
image = china[150:220, 130:250]
#print(image)
print(china.shape)
print(image.shape)
height, width, channels = image.shape
image_grayscale = image.mean(axis=2).astype(np.float32)
print(image_grayscale.shape)
images = image_grayscale.reshape(1, height, width, 1)
images.shape

(427, 640, 3)
(70, 120, 3)
(70, 120)


(1, 70, 120, 1)

In [3]:
my_multi_arr = np.arange(20).reshape(4,5)
my_multi_arr_portion = my_multi_arr[2:4, 2:5]
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [8]:
#Convert 2-D or 3-D array to 1-D array
import numpy as np

my_2d_arr = np.arange(20).reshape(4,5)
my_1d_arr = my_2d_arr.ravel()
print(my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
#Addition and Subtraction of Arrays (element wise)

a_arr = np.array((60, 70, 80, 90))
b_arr = np.arange(4)
c_arr = a_arr + b_arr
print(c_arr)

d_arr = np.array((60, 70, 80, 90))
e_arr = np.arange(4)
f_arr = d_arr - e_arr
print(f_arr)

[60 71 82 93]
[60 69 78 87]


In [1]:
#Element wise product of two arrays (using *)
import numpy as np

A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )
M_arr = A_arr * B_arr
print(M_arr)

#Matrix multiplication of two arrays (using dot)
C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )
P_arr = np.dot(C_arr,D_arr)
print(P_arr)


[[10 72]
 [ 4 42]]
[[19 94]
 [15 74]]


In [18]:
#Element wise division of two arrays (using /)
R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array([ [2, 10], [4, 5] ] )
T_div = R_div/S_div
print(T_div)

#Integer division of two arrays (using //)
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array([ [2, 10], [8, 3] ] )
T_int_div = R_int_div//S_int_div
print(T_int_div)

#Modulus division of two arrays (using %)
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array([ [2, 10], [8, 3] ] )
T_mod = R_mod%S_mod
print(T_mod)

[[12.5  6.5]
 [10.   2.8]]
[[12  6]
 [ 5 23]]
[[0 5]
 [0 1]]


In [37]:
#Element wise exponentition of an array using another exponent array(using **)

R_exp = np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )
T_exp = R_exp**S_exp
print(T_exp)

[[  16 1024]
 [  81 1024]]


In [47]:
#Get all the elements of an array which are less than 45
U = np.array([ [ 22, 45], [90, 4 ] ] )
print(U[U<45])

[22  4]


In [55]:
#Statistical Functions

X_stat = np.array([ [ 1, 2, 3], [ 4, -5, 6] ])
#Mean
print("mean = ", X_stat.mean())

#Variance
print("Variance = ", X_stat.var())

#Standard Deviation
print("Standard Deviation = ", X_stat.std())

#Minimum
print("min = ", X_stat.min())

#Maximum
print("max = ", X_stat.max())

#Sum
print("sum = ", X_stat.sum())

#Product
print("product = ", X_stat.prod())

mean =  1.8333333333333333
Variance =  11.805555555555557
Standard Deviation =  3.435921354681384
min =  -5
max =  6
sum =  11
product =  -720


In [68]:
#Sum across axes
Z = np.arange(18).reshape(2,3,3)
print(Z)
print(Z.sum(axis=0))
print(Z.sum(axis=1))
print(Z.sum(axis=2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[ 9 11 13]
 [15 17 19]
 [21 23 25]]
[[ 9 12 15]
 [36 39 42]]
[[ 3 12 21]
 [30 39 48]]


In [74]:
#Transpose
N = np.arange(6).reshape(3,2)
print(N)
print("Transpose = ", N.T)

[[0 1]
 [2 3]
 [4 5]]
Transpose =  [[0 2 4]
 [1 3 5]]


In [85]:
#Broadcasting - adjust the shape of one or both of the arrays to bring them to required matching shape
X_broad = np.ones((3,3))
print(X_broad)
Y_broad = np.arange(3)
print(Y_broad)
Z_broad = X_broad+Y_broad
print(Z_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
